### ISSUE TITLE
Assembly Name and Default Namespace not set during project creation

### ISSUE THREAD

**Issue by milleraa** [SubPointSolutions/spmeta2-vsixextensions#38]
Hi.

After projects creation by SPMeta2 template Assembly Name and Default Namespace are not set to the name on project. They always are SPMeta2.VS.CSharp.ProvisionConsole.

Versions: SPMeta2 Extension 1.2.90.25, VS 2015 update 3.

**Comment by SubPointSupport** [comment]
Thanks for reporting this. Bug for sure, will fix it.
